:PROPERTIES:
:ID:       468f39e7-f10e-43fe-8375-202e3d957882
:END:
#+title: Principal component analysis

* Principal Component Analysis (PCA)
- PCA is used to reduce dimensionality of the data. This is done by selecting few directions that accounts
  for most variances in the data.

** Maths for PCA and why it works
suppose we have a dataset that has $$m$$ rows of data and $$n$$ columns like

| x1 | x2 | x3 | x4 | xn |
| y1 | y2 | y3 | y4 | yn |
| .. | .. | .. | .. | .. |

1. Make the mean of all columns zero.

   - [[https://www.youtube.com/watch?v=FgakZw6K1QQ&t=200s][why we make mean of all columns zero?]]

2. now, we have to find a best fit lines in all n new directions. These all new lines will be
   independent of each other. To find the best fit line what we have to do is maximize the distance between
   projected point on that line and the origin.

   - =why the new lines must be independent?=
     This because every line must account for variations in
     different directions.
     For eg if we have 2-D data then a line will account for variance in X-axis i.e horizontal variations but
     what about vertical variations ie along Y-axis that's why the new lines must be independent.

   - [[https://www.youtube.com/watch?v=FgakZw6K1QQ&t=305s][Why we maximize the distance?]]

3. The best fit line of the particular direction will be the eigenvector of the covariance matrix of the data.

   - =why we take covariance matrix of the data?=
     Because [[id:d7ad3726-5138-4f5c-9a0a-e3262542fae4][covariance]] measures the similarity between two different dimensions of data. Creating this
     matrix we tell us the "similarity" between two different columns of our data.

   - [[https://www.youtube.com/watch?v=dhK8nbtii6I][why the best fit line will always be eigenvector? Proof]]

   - The eigenvalue will determine the importance of the eigenvector ie. how much that vector accounts for the
     variances is the dataset?

4. After getting the eigenvector we can sort them according to there eigenvalues and use most important
   eigenvector to project the data.

** Resources
1. [[https://towardsdatascience.com/a-one-stop-shop-for-principal-component-analysis-5582fb7e0a9c][Medium Article]]
2. [[file:///home/paradox/Zotero/storage/ICKBWBIH/OUCS-2002-12.pdf][PDF that covers PCA with background mathematics]]
