:PROPERTIES:
:ID:       e0d37df0-5d03-4a29-b832-09aae248f79d
:END:
#+title: Theorems And Properties (Sequences in R)

#+filetags: :Calculus:Multivariable Calculus:Analysis:

#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheord.setup

* 2.1 Definition

 A sequence of real numbers $\{x_n\}$ is said to converge to a real number $a \in \mathbb{R}$. If and only if for every $\epsilon > 0$ there is an $N \in \mathbb{N}$ (which in general depends on $\epsilon$ ) such that
                            $n \geq N$ implies $|x_n - a| < \epsilon$


* 2.4 Remark

A Sequence can have at most one limit.

* 2.5 Definition

By a subsequence of a sequence $\{x_n\}_{n\in\mathbb{N}}$, we shall mean a sequence of the form $\{x_{n_k}\}_{k\in\mathbb{N}}$, where each $n_k \in \mathbb{N}$ and $n_1 < n_2<$ ...

* 2.6 Remark

If $\{x_n\}_{n\in\mathbb{N}}$ converges to $a$ and $\{x_{n_k}\}_{k \in \mathbb{N}}$ is any subsequence of $\{x_n\}_{n\in\mathbb{N}}$, then $x_{n_k}$ converges to $a$ as $k \rightarrow \infty$

* 2.7 Definition

Let $\{x_n\}$ be a sequence of real numbers.

1) The sequence $\{x_n\}$ is said to be /bounded above/ if and only if the set $\{x_n : n \in \mathbb{N}\}$ is bounded above.
2) The sequence $\{x_n\}$ is said to be /bounded below/ if and only if the set $\{x_n : n \in \mathbb{N}\}$ is bounded below.
3) $\{x_n\}$ is said to be /bounded/ if and only if it is both bounded above and below.

* 2.8 Theorem

Every /convergent sequence/ is /bounded/.

* 2.9 Theorem [Squeeze / Sandwich Theorem]

Suppose that $\{x_n\}, \{y_n\} and \{w_n\}$ are /real/ sequences.

1) If $x_n \rightarrow a$ and $y_n \rightarrow a$ (the SAME $a$) as $n \rightarrow \infty$, and if there is an $N_0 \in \mathbb{N}$ such that
                                  $x_n \leq w_n \leq$ for $n \geq N_0$
   then $w_n \rightarrow a$ as $n \rightarrow \infty$

2) If $n \rightarrow 0$ as $n \rightarrow \infty$ and $\{y_n\}$ is /bounded/ , then $x_ny_n \rightarrow 0$ as $n \rightarrow \infty$


* 2.11 Theorem

    Let $E \subset \mathbb{R}$. If $E$ has a finite supremum (respectively, a finite infimum), then there is a sequence $x_n \in E$ such that $x_n \rightarrow$ sup$E$ (respectively, a sequence $y_n \in E$ such that $y_n \rightarrow$ inf$E$) as $n \rightarrow \infty$.

* 2.12 Theorem

Suppose $\{x_n\}$ and $\{y_n\}$ are real sequences and that $\alpha \in \mathbb{R}$. If $\{x_n\}$ and $\{y_n\}$ are convergent then

1) $\lim_{n \rightarrow \infty} (x_n + y_n) = lim_{n \rightarrow \infty} x_n + lim_{n \rightarrow \infty} y_n$
2) $\lim_{n \rightarrow \infty} (\alpha \cross x_n) = \alpha \cross lim_{n \rightarrow \infty} x_n$
3) $\lim_{n \rightarrow \infty} (x_n \cross y_n) = (lim_{n \rightarrow \infty} x_n) \cross (lim_{n \rightarrow \infty} y_n)$
4) $\lim_{n \rightarrow \infty}\frac{x_n}{y_n} = \frac{lim_{n \rightarrow \infty} x_n}{lim_{n \rightarrow \infty} y_n}$.

* 2.14 Definition

 Let $\{x_n\}$ be a sequence of a real numbers.
 1) $\{x_n\}$ is said to /diverge/ to $+\infty$ if and only if for each $M \in \mathbb{R}$ there is an $N \in \mathbb{N}$ such that
                    $n \geq N$ implies $x_n > M$
 2) $\{x_n\}$ is said to /diverge/ to $-\infty$ if and only if for each $M \in \mathbb{R}$ there is an $N \in \mathbb{N}$ such that
                    $n \geq N$ implies $x_n < M$

* 2.15 Theorem

Suppose that $\{x_n\}$ and $\{y_n\}$ are /real sequences/ such that $x_n \rightarrow +\infty$ (respectively $x_n \rightarrow -\infty$) as $n \rightarrow \infty$.

1) If $y_n$ is /bounded below/ (respectively, $y_n$ is /bounded above/), then
        $\lim_{n \rightarrow \infty} (x_n + y_n) = +\infty$
