:PROPERTIES:
:ID:       dd5776f4-4c0a-47c7-8424-e519aaa01b78
:END:
#+title: Addition

#+filetags: :Calculus:Multivariable Calculus:Analysis:

#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheord.setup


* Axiom 2.1.
    $0$ is a /natural number/.

* Axiom 2.2
    If $n$ is a /natural number/, then $n++$ is also a /natural number/.

* Definition 2.1.3
    We define $1$ to be number $0++$, $2$ to be $(0++)++$, $3$ to be $((0++)++)++$, so on and so forth.

* Axiom 2.3
    $0$ is not the successor of any /natural number/; i.e. $n++ \neq 0 \text{ } \forall \text{ } n$.

* Axiom 2.4
    Different natural numbers must have different successors; i.e, if $n,m$ are natural numbers and $n \neq m$, then
    $n++ \neq m++$, /Equivalently/, if $n++ = m++$, then we must have $n = m$.

* Axiom 2.5 (Principle of mathematical induction).
    Let $P(n)$ be any property pertaining to a natural number $n$. Suppose that $P(0)$ is true, and suppose that whenever $P(n)$ is true, $P(n++)$ is also true. Then $P(n)$ is true for every natural number n.


* Proposition 2.1.11:
    A certain property $P(n)$ is true for every natural number n.

* Assumption 2.6 (Informal)
    There exists a number system $\mathbb{N}$, whose elements we will call natural numbers, for which /Axioms 2.1-2.5/ are true.

* Proposition 2.1.16 (Recursive definitions)
    Suppose for each natural number n, we have some function $f_n : \mathbb{N} \rightarrow \mathbb{N}$ from the natural numbers to the natural numbers.
    Let $c$ be a natural number. Then we can assign a unique natrual number $a_n$ to each natural number n, such that $a_0 = c$ and $a_{n++} = f_n(a_n)$ for each natural number n.

* Definition 2.2.1 (Addition of natural numbers).
    Let $m$ be a natural number. To add zero to $m$, we define $0 + m := m$. Now suppose inductively that we have defined how to add n to m. Then we can add $n++$ to $m$ by definition $(n++)+m := (n+m)++$.

* Lemma 2.2.2:
    For any natural number $n$, $n + 0 = n$.

* Lemma 2.2.3:
    For any natural numbers n and m, $n + (m++) = (n+m)++$.

* Proposition 2.2.4 (Addition is commutative).
    For any natural numbers $n$ and $m$, $n + m = m + n$.

* Proposition 2.2.5 (Addition is associative).
    For any natural numbers $a,b,c$, we have $(a + b) + c = a + (b + c)$.

* Proposition 2.2.6 (Cancellation law).
    Let $a,b,c$ be natural numbers such that $a + b = a + c$. Then we have $b = c$.

* Definition 2.2.7
    A natural number $n$ is said to be /positive/ iff it is not equal to 0.

* Proposition 2.2.8
    If $a$ is a /positive/ and $b$ is a /natural number/, then $a + b$ is /positive/ (and hence $b + a$ is also, by Proposition 2.2.4).

* Corollary 2.2.9
    If $a$ and $b$ are natural numbers such that $a + b = 0$, then $a = 0$ and $b = 0$.

* Lemma 2.2.10
    Let $a$ be a positive number. Then there exists exactly one natural number $b$ such that $b++$ = $0$.

* Definition 2.2.11 (Ordering of the natural numbers).
    Let $n$ and $m$ be natural numbers. We say that $n$ is /greater than or equal to m/, and we write $n \geq m$, iff we have
    $n = m + a$ for some natural number a. We say that $n$ is /strictly greater than m/, and write $n > m$ iff $n \geq m$ and $n \neq m$.
* Proposition 2.2.12 (Basic properties of order for natural numbers).
    Let $a,b,c$ be /natural numbers/. Then
        1) (Order is reflexive) $a \geq a$
        2) (Order is transitive) If $a \geq b$ and $b \geq c$, then $a \geq c$.
        3) (Order is anti-symmetric) If $a \geq b$ and $b \geq a$, then $a = b$.
        4) (Addition preservers order) $a \geq b$ iff $a + c \geq b + c$.
        5) $a < b$ iff $a++ \leq b$.
        6) $a < b$ iff $b = a + d$ for some positive number d.

* Proposition 2.2.13 (Trichotomy of order for natural number).
    Let $a$ and $b$ be /natural numbers/. Then exactly one of the following statements is true: $a < b, a = b$ or $a > b$.

* Proposition 2.2.14 (Strong principle of induction)
    Let $m_0$ be a /natural number/, and let $P(m)$ be a property pertaining to an arbitrary natural number $m$.
    Suppose that for each $m \geq m_0$, we have the following implication: if $P(m^')$ is true for all natural numbers $m_0 \leq m^{'} \leq m$, then $P(m)$ is also true. Then we can conclude that $P(m)$ is true for all natural numbers $m \geq m_0$.
